### PR TITLE
Add seeder from beyondcoin.io hosted by Kristian Kramer

### PR DESCRIPTION
**Pull request by Tech1k**

### CODE REVIEW

**Review by jakesum — COMMENTED** [review]
does not appear to connect on nslookup.  Please review and resubmit

**Comment by Tech1k** [comment]
I'll reopen when fixed.

**Comment by Tech1k** [comment]
Fixed https://dnschecker.org/#A/sumdnsseed.beyondcoin.io (the A record is still getting resolved by some DNS servers, but it's working).

**Comment by 5053s** [comment]
Meets consensus criteria as seeder - merged

**Pull request merged**
